## The Tensorflow Trials

For much of the past week, you've been using tensors with your Deep Learning models. Over the course of today's challenges, you'll be manipulating tensors extensively and working with some unconventional model architectures. 


In this warm up, you'll be introduced to some new methods. 

All the methods here are going to make tackling challenges later in the day 100x easier, so if you do get stuck later on, make sure you come back here to see how you achieved the right answers. 

In [28]:
import tensorflow as tf

A:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


A) Use `tf.ones` to create a tensor `a` filled with ones of shape (3,3).

In [20]:
pass 

tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

B) Use tf.expand_dims to make `a` an object of shape (1,3,3) called `b`.

In [21]:
import tensorflow as tf
a = tf.ones((3,3))
b = tf.expand_dims(a, 0)


C) Create a tensor `c` filled with zeroes of size (9,1)

In [22]:
c = tf.zeros((9,1))

D) Reshape `c` to be of shape (1, 3, 3). Name it `d`.

In [23]:
d = tf.reshape(c, (1, 3, 3))


E) Use `tf.matmul` to matrix multiply `b` and `d` with each other and now assign the tensor to `e`. 

In [24]:
e = tf.matmul(b, d)


F) Below is a `numpy` array. Convert it to a tensor named `array_tensor`. Then use `tf.cast` to ensure it is of dtype `float` not `int`. Assign the result to `f`.

In [29]:
import numpy as np

g = np.array([1, 2, 3, 4])
array_tensor = tf.convert_to_tensor(np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]))
f = tf.cast(array_tensor, dtype=tf.float32)


In [35]:
array = np.array([[
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [33]:
g = f[:, -1]  # Select the last column of f
f = tf.expand_dims(g, axis=1)
print(f)


tf.Tensor(
[[ 4.]
 [ 8.]
 [12.]
 [16.]], shape=(4, 1), dtype=float32)


G) Select the values in the __last column__ of `f` and save this to `g`. To be clear, `g` should have shape (4,) and contain the values `3,3,6,9`. 

In [36]:
g = f[:, -1]  # Select the last column of f
print(g)


tf.Tensor([ 4.  8. 12. 16.], shape=(4,), dtype=float32)


H) Expand the dimensions of g so that it's of shape (4,1). Assign this to `h`.

In [40]:
h = tf.matmul(e, f, transpose_b=True)


2024-05-24 15:34:47.124500: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [1,3,3], In[1]: [4,1]


InvalidArgumentError: {{function_node __wrapped__BatchMatMulV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [1,3,3], In[1]: [4,1] [Op:BatchMatMulV2] name: 

H) Multiply e with f, using `tf.matmul` with the optional `transpose_b` argument (`e` must come first in your positional arguments, then `f`). Assign this to `h`.

In [38]:
i = tf.linalg.band_part(tf.ones((10, 10)), -1, 0)


I) Create a `(10,10)` tensor filled with ones. Then use `tf.linalg.band_part()` to mask out the upper triangle of the matrix (i.e. the upper triangle should all be 0s). Assign to `i`.

In [ ]:
pass  # YOUR CODE HERE

J) Take the `number_list` below and make it a tensor. Assign it to `j`.

In [ ]:
number_list = [1,2,3,4,8]

In [ ]:
pass  # YOUR CODE HERE

K) Use `tf.expand_dims` to make `j` into a tensor of shape (1,5). Assign to `k`.

In [ ]:
k = tf.expand_dims(j, axis=0)


L) Use `tf.tile` to repeat `k` 50 times, with an eventual shape of `(50,5)`. Assign to `l`.

In [ ]:
l = tf.tile(k, multiples=(50, 1))


M) Use a simple Boolean statement to create a tensor containing `True` values for where `l` is 3  and `False` for where it is not 3. Assign to `m`

In [ ]:
m = tf.equal(l, 3)


N) Divide every value in you variable `l` (read as "L") by 3. Assign to `n`.

In [ ]:
pass  # YOUR CODE HERE

O) Use `tf.concat()` to take the list of two tensors below of shape (5,5) and (5,5) each and turn them into a final tensor of shape (10,5). Assign to `o`. Think carefully about the concation axis.

In [ ]:
tensor_list = [tf.ones((5,5)), tf.ones((5,5))]

In [ ]:
pass  # YOUR CODE HERE

### Check your answers

In [39]:
from nbresult import ChallengeResult

result = ChallengeResult('tensors',
                            a = a,
                            b = b,
                            c = c,
                            d_shape = d.shape,
                            e = e,
                            f = f, 
                            g = g,
                            h = h,
                            i = i,
                            j = j,
                            k = k,
                            l = l,
                            m = m,
                            n = n, 
                            o_shape = o.shape
)

result.write()
print(result.check())

NameError: name 'h' is not defined

### Great work 🔥

Now it's time to get stuck into some modelling!